In [1]:
import numpy as np
import pandas as pd
from bracket_picker import Bracketeer

In [2]:
b = Bracketeer()
# b.get_tourney_teams()
# b.final_68

In [3]:
b.print_polls()

Index(['Team', 'Conf', 'WL', 'Rank', 'Mean', 'Trimmed', 'Median', 'StDev',
       '7OT', 'AP', 'BBT', 'BIH', 'BNT', 'BWE', 'DAV', 'DES', 'DII', 'DOK',
       'DOL', 'FAS', 'FSH', 'HAS', 'JJK', 'JNG', 'KPI', 'KPK', 'LEF', 'LMC',
       'MAS', 'MGS', 'MMG', 'MOR', 'NET', 'PGH', 'PIR', 'POM', 'REW', 'RT',
       'RTP', 'SAG', 'SFX', 'SGR', 'SMN', 'SP', 'SPR', 'STH', 'TPR', 'TRK',
       'TRP', 'USA', 'WIL', 'WOL', 'ZAM', ''],
      dtype='object')

In [4]:
b.get_conferences()

array(['ACC', 'WCC', 'B10', 'SEC', 'B12', 'AAC', 'MWC', 'MAC', 'BE', 'SC',
       'A10', 'P12', 'OVC', 'WAC', 'ASUN', 'BWC', 'CAA', 'AEC', 'Ivy',
       'CUSA', 'SBC', 'SL', 'HL', 'MVC', 'BSC', 'BSo', 'PL', 'SLC',
       'MAAC', 'SWAC', 'NEC', 'MEAC'], dtype=object)

In [5]:
# # # Want to work on adding partial conference winners functionality
conference_winners = {conf:None for conf in b.get_conferences()}

conference_winners['OVC'] = 'Murray St'
conference_winners['BSo'] = 'Gardner Webb'
conference_winners['MVC'] = 'Bradley'
conference_winners['ASUN']= 'Liberty'

In [6]:
for conf, team in conference_winners.items():
    if team is not None:
        print(conf, team)

OVC Murray St
ASUN Liberty
MVC Bradley
BSo Gardner Webb

In [7]:
comp_polls = ['POM','7OT','SAG','NET','MAS']

def rank_calc(x, y):
    if np.isnan(y) :
        return x
    else:
        return ((3 * x + y) / 4.)

b.get_tourney_teams(
    comp_polls = comp_polls,
    rank_calc_func = rank_calc,
    conf_winners=conference_winners
)

In [8]:
b.final_68

               Team  Conf  comp_mean  human_mean  final_rank  seed
1           Gonzaga   WCC        2.0         1.0       1.750     1
0          Virginia   ACC        1.8         2.0       1.850     1
2              Duke   ACC        3.0         5.0       3.500     1
3    North Carolina   ACC        4.0         3.0       3.750     1
6          Kentucky   SEC        7.2         4.0       6.400     2
7          Michigan   B10        8.2        10.5       8.775     2
4       Michigan St   B10        9.8         6.5       8.975     2
5         Tennessee   SEC        9.4         8.0       9.050     2
8        Texas Tech   B12       11.4         6.5      10.175     3
9           Houston   AAC       10.2        10.5      10.275     3
10           Purdue   B10       10.8        12.5      11.225     3
11              LSU   SEC       14.2         9.0      12.900     3
13    Virginia Tech   ACC       13.8        15.5      14.225     4
12           Kansas   B12       14.8        17.5      15.475     4
14       Florida St   ACC       17.8        12.5      16.475     4
16           Nevada   MWC       18.8        15.5      17.975     4
17           Auburn   SEC       16.8        23.0      18.350     5
15        Wisconsin   B10       18.2        19.0      18.400     5
18          Buffalo   MAC       20.6        17.0      19.700     5
20         Maryland   B10       20.0        21.0      20.250     5
22       Louisville   ACC       20.4         NaN      20.400     6
19        Kansas St   B12       22.6        14.5      20.575     6
21   Mississippi St   SEC       21.0         NaN      21.000     6
24          Wofford    SC       25.2        20.0      23.900     6
23        Villanova    BE       26.0        25.0      25.750     7
26          Iowa St   B12       26.6         NaN      26.600     7
27       Cincinnati   AAC       28.0        23.5      26.875     7
25        Marquette    BE       28.4        22.5      26.925     7
29              UCF   AAC       28.6         NaN      28.600     8
31          Clemson   ACC       30.0         NaN      30.000     8
..              ...   ...        ...         ...         ...   ...
39      Mississippi   SEC       40.6         NaN      40.600    10
33         NC State   ACC       44.0         NaN      44.000    10
40              TCU   B12       44.6         NaN      44.600    11
43        Creighton    BE       44.8         NaN      44.800    11
55          Penn St   B10       44.8         NaN      44.800    11
41           Baylor   B12       45.8         NaN      45.800    11
45        Murray St   OVC       47.8         NaN      47.800    11
36             Iowa   B10       49.0         NaN      49.000    11
47          Ohio St   B10       49.2         NaN      49.200    12
49    New Mexico St   WAC       50.4         NaN      50.400    12
44          Belmont   OVC       52.6         NaN      52.600    12
61          Alabama   SEC       53.2         NaN      53.200    12
75          Liberty  ASUN       80.6         NaN      80.600    13
73          Hofstra   CAA       80.8         NaN      80.800    13
77          Vermont   AEC       83.0         NaN      83.000    13
79             Yale   Ivy       87.8         NaN      87.800    13
72        UC Irvine   BWC       88.8         NaN      88.800    14
97      Ga Southern   SBC       99.8         NaN      99.800    14
92     Old Dominion  CUSA      105.8         NaN     105.800    14
100      N Kentucky    HL      106.6         NaN     106.600    14
98      S Dakota St    SL      108.2         NaN     108.200    15
123         Montana   BSC      116.6         NaN     116.600    15
131         Colgate    PL      127.0         NaN     127.000    15
140     Abilene Chr   SLC      155.2         NaN     155.200    15
160         Bradley   MVC      167.6         NaN     167.600    16
169    Gardner Webb   BSo      176.8         NaN     176.800    16
206           Rider  MAAC      205.2         NaN     205.200    16
213     F Dickinson   NEC      216.8         NaN     216.800    16
215    Prairie View  SWAC      219.8         NaN     219.800    16
241      Norfolk St  MEAC      258.6         NaN     258.600    16

[68 rows x 6 columns]

In [11]:
b.fill_bracket()

# 2017 auto bids
auto_bids = ['SMU', 'Michigan', 'Troy', 'Kentucky', 'Princeton', 'Rhode Island',
            'Arizona', 'UC Davis', 'New Mexico St', 'New Orleans', 'Duke',
            'Villanova', 'North Dakota', 'MTSU', 'Kent', 'NC Central', 'Iowa St',
            'Nevada', 'TX Southern', 'Vermont', 'Bucknell', 'S Dakota St',
            'Gonzaga', 'N Kentucky', "Mt St Mary's", 'Iona', 'UNC Wilmington',
            'ETSU', 'FL Gulf Coast', 'Wichita St', 'Winthrop', 'Jacksonville St']
len(auto_bids)

In [ ]:
b.final_68