In [1]:
import numpy as np
import pandas as pd
from bracket_picker import Bracketeer

In [2]:
b = Bracketeer()
# b.get_tourney_teams()
# b.final_68

In [3]:
b.print_polls()

Index(['Team', 'Conf', 'WL', 'Rank', 'Mean', 'Trimmed', 'Median', 'StDev',
       '7OT', 'AWS', 'BIH', 'BNT', 'COL', 'DCI', 'DES', 'DII', 'DOK', 'DOL',
       'EBP', 'ESR', 'FAS', 'FSH', 'JJK', 'KPI', 'KPK', 'LEF', 'MAS', 'MGS',
       'MOR', 'NET', 'PGH', 'PIG', 'PIR', 'POM', 'REW', 'RT', 'RTH', 'RTP',
       'SAG', 'SFX', 'SGR', 'SMN', 'SP', 'SPR', 'TPR', 'TRP', 'USA', 'WIL',
       'WLK', 'WOL', 'YAG', 'ZAM', ''],
      dtype='object')

In [4]:
b.get_conferences()

array(['ACC', 'WCC', 'B10', 'SEC', 'AAC', 'B12', 'MAC', 'BE', 'MWC', 'SC',
       'A10', 'P12', 'WAC', 'OVC', 'ASUN', 'BWC', 'AEC', 'Ivy', 'CAA',
       'CUSA', 'SBC', 'HL', 'MVC', 'SL', 'BSC', 'PL', 'BSo', 'SLC',
       'MAAC', 'SWAC', 'NEC', 'MEAC'], dtype=object)

In [5]:
# # # Want to work on adding partial conference winners functionality
conference_winners = {conf:None for conf in b.get_conferences()}

conference_winners['OVC'] = 'Murray St'
conference_winners['BSo'] = 'Gardner Webb'
conference_winners['MVC'] = 'Bradley'
conference_winners['ASUN']= 'Liberty'
conference_winners['SC']  = 'Wofford'
conference_winners['MAAC']= 'Iona'
conference_winners['HL']  = 'N Kentucky'
conference_winners['NEC'] = 'F Dickinson'
conference_winners['CAA'] = 'Northeastern'
conference_winners['SL']  = 'N Dakota St'
conference_winners['WCC'] = "St Mary's CA"
conference_winners['PL']  = 'Colgate'

In [6]:
comp_polls = ['POM','DOK','SAG','NET','EBP']

def rank_calc(x, y):
    if np.isnan(y) :
        return x
    else:
        return ((3 * x + y) / 4.)

b.get_tourney_teams(
    comp_polls = comp_polls,
    rank_calc_func = rank_calc,
    conf_winners=conference_winners
)

KeyError: "['AP'] not found in axis"

In [6]:
b.final_68

               Team  Conf  comp_mean  human_mean  final_rank  seed
2           Gonzaga   WCC        1.6         1.0       1.450     1
0          Virginia   ACC        1.4         2.0       1.550     1
1              Duke   ACC        3.0         5.0       3.500     1
3    North Carolina   ACC        5.0         3.0       4.500     1
6          Kentucky   SEC        6.4         4.0       5.800     2
4       Michigan St   B10        5.6         6.5       5.825     2
5         Tennessee   SEC        6.4         8.0       6.800     2
8        Texas Tech   B12        8.2         6.5       7.775     2
7          Michigan   B10        8.8        10.5       9.225     3
10           Purdue   B10       10.0        12.5      10.625     3
9           Houston   AAC       12.6        10.5      12.075     3
13    Virginia Tech   ACC       12.0        15.5      12.875     3
14       Florida St   ACC       16.0        12.5      15.125     4
11              LSU   SEC       17.2         9.0      15.150     4
15        Wisconsin   B10       14.2        19.0      15.400     4
17           Auburn   SEC       13.2        23.0      15.650     4
12           Kansas   B12       16.4        17.5      16.675     5
16           Nevada   MWC       17.8        15.5      17.225     5
19        Kansas St   B12       21.8        14.5      19.975     5
18          Buffalo   MAC       22.4        17.0      21.050     5
22       Louisville   ACC       21.8         NaN      21.800     6
26          Iowa St   B12       21.8         NaN      21.800     6
24          Wofford    SC       23.4        20.0      22.550     6
23        Villanova    BE       22.2        25.0      22.900     6
21   Mississippi St   SEC       23.0         NaN      23.000     7
20         Maryland   B10       23.8        21.0      23.100     7
25        Marquette    BE       28.2        22.5      26.775     7
32         NC State   ACC       27.6         NaN      27.600     7
27       Cincinnati   AAC       29.4        23.5      27.925     8
31          Clemson   ACC       29.0         NaN      29.000     8
..              ...   ...        ...         ...         ...   ...
38      Mississippi   SEC       39.6         NaN      39.600    10
35             Iowa   B10       41.8         NaN      41.800    10
37          Utah St   MWC       42.2         NaN      42.200    11
43          Indiana   B10       43.0         NaN      43.000    11
40              TCU   B12       43.6         NaN      43.600    11
55          Penn St   B10       44.2         NaN      44.200    11
54         Nebraska   B10       44.6         NaN      44.600    11
34       Washington   P12       44.8         NaN      44.800    11
46        Creighton    BE       46.4         NaN      46.400    12
45          Ohio St   B10       46.4         NaN      46.400    12
44        Murray St   OVC       51.2         NaN      51.200    12
49    New Mexico St   WAC       57.6         NaN      57.600    12
75          Liberty  ASUN       77.2         NaN      77.200    13
77          Vermont   AEC       81.6         NaN      81.600    13
79             Yale   Ivy       86.0         NaN      86.000    13
71        UC Irvine   BWC       86.6         NaN      86.600    13
82     Northeastern   CAA       88.0         NaN      88.000    14
101      N Kentucky    HL      106.8         NaN     106.800    14
98      Ga Southern   SBC      109.6         NaN     109.600    14
92     Old Dominion  CUSA      110.2         NaN     110.200    14
125         Montana   BSC      129.2         NaN     129.200    15
131         Colgate    PL      137.0         NaN     137.000    15
140     Abilene Chr   SLC      155.4         NaN     155.400    15
156         Bradley   MVC      166.8         NaN     166.800    15
168    Gardner Webb   BSo      171.6         NaN     171.600    16
212            Iona  MAAC      197.4         NaN     197.400    16
203     N Dakota St    SL      206.4         NaN     206.400    16
213     F Dickinson   NEC      216.8         NaN     216.800    16
211     TX Southern  SWAC      220.4         NaN     220.400    16
238      Norfolk St  MEAC      260.8         NaN     260.800    16

[68 rows x 6 columns]

In [7]:
b.fill_bracket()

# 2017 auto bids
auto_bids = ['SMU', 'Michigan', 'Troy', 'Kentucky', 'Princeton', 'Rhode Island',
            'Arizona', 'UC Davis', 'New Mexico St', 'New Orleans', 'Duke',
            'Villanova', 'North Dakota', 'MTSU', 'Kent', 'NC Central', 'Iowa St',
            'Nevada', 'TX Southern', 'Vermont', 'Bucknell', 'S Dakota St',
            'Gonzaga', 'N Kentucky', "Mt St Mary's", 'Iona', 'UNC Wilmington',
            'ETSU', 'FL Gulf Coast', 'Wichita St', 'Winthrop', 'Jacksonville St']
len(auto_bids)

In [ ]:
b.final_68